development:
  clients:
    default:
      database: usgs
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: usgs
      hosts:
        - 127.0.0.1:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
